
name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Start Kong stack if docker-compose.yml exists in repo
      - name: Start Kong (docker-compose)
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: |
          docker compose up -d
          # wait up to 10 min for Kong Manager (adjust if needed)
          npx wait-on -t 600000 http://localhost:8002

      - name: Run Cypress (Chrome headless)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.ts
          spec: "cypress/e2e/**/*.cy.ts"

      # Artifacts
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: reposts/screenshots
          if-no-files-found: ignore

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
          if-no-files-found: ignore

      - name: Teardown
        if: ${{ always() && hashFiles('docker-compose.yml') != '' }}
        run: docker compose down --remove-orphans
